# $\Lambda$CDM tests with ML lkl prof code

In [1]:
from MP_classes_lkl_prof_functions import *
from MP_to_Cobaya_functions import *

In [2]:
test = lkl_prof('/home2/karwal/lkl_prof/lcdm_mp_mcmc/', 'lcdm_mp_mcmc', 'H0')

test.prof_incr = -0.1
test.prof_max = 72
test.prof_min = 65.
test.processes = 2

In [3]:
test.check_mcmc_chains(read_all_chains=True)

check_mcmc_chains: Looking for files: /home2/karwal/lkl_prof/lcdm_mp_mcmc/2022-07-12_100000_
check_mcmc_chains: Reading all chains:
2022-07-12_10__1.txt
2022-07-12_100000__1.txt
2022-07-12_100000__2.txt
2022-07-12_100000__3.txt
2022-07-12_100000__4.txt
2022-07-12_100000__5.txt
2022-07-12_100000__6.txt


True

In [4]:
test.check_mcmc_convergence()

check_mcmc_convergence: Chains not converged. Current R-1 = 17.672 while R-1 wanted = 0.050. 
Resume MCMC. 


False

In [5]:
# test.mcmc()

In [6]:
test.global_min(run_glob_min=False);

check_global_min: Found minimum with file name lcdm_mp_mcmc
global_min: File not found. Starting a new file now: /home2/karwal/lkl_prof/lcdm_mp_mcmc/lcdm_mp_mcmc_-H0_lkl_profile.txt



/home2/karwal/lkl_prof/MP_classes_lkl_prof_functions.py:308: UserWarning: loadtxt: Empty input file: "/home2/karwal/lkl_prof/lcdm_mp_mcmc/lcdm_mp_mcmc_-H0_lkl_profile.txt"
  lkl_prof_table = np.loadtxt(self.chains_dir + self.info_root + extension)


In [7]:
test.global_ML

{'omega_b': 0.02237694,
 'omega_cdm': 0.1195916,
 'H0': 67.61452,
 'n_s': 0.9679088,
 'A_s': 2.110612e-09,
 'tau_reio': 0.05680741,
 'A_cib_217': 45.55986,
 'xi_sz_cib': 0.8614257,
 'A_sz': 6.608623,
 'ps_A_100_100': 251.4162,
 'ps_A_143_143': 55.89322,
 'ps_A_143_217': 59.28295,
 'ps_A_217_217': 124.3008,
 'ksz_norm': 0.7709484,
 'gal545_A_100': 8.819424,
 'gal545_A_143': 11.15055,
 'gal545_A_143_217': 20.32142,
 'gal545_A_217': 95.50828,
 'galf_TE_A_100': 0.1177694,
 'galf_TE_A_100_143': 0.1356197,
 'galf_TE_A_100_217': 0.4764099,
 'galf_TE_A_143': 0.2231539,
 'galf_TE_A_143_217': 0.658525,
 'galf_TE_A_217': 2.088564,
 'calib_100T': 0.9996958,
 'calib_217T': 0.9982091,
 'A_planck': 1.000634,
 'M': -19.41938,
 'age': 13.78533,
 'rs_rec': 144.6217,
 '100*theta_s': 1.042093,
 'sigma8': 0.8121466,
 'Omega_m': 0.3119451,
 'Omega_Lambda': 0.6879757,
 '-logLike': 1905.15}

In [8]:
test.init_lkl_prof()

67.61452

In [9]:
test.run_lkl_prof(time_mins=True)

match_param_line: Only one entry in file, checking that entry 
!!!!!!!!!!!!!!!!!
run_minimizer: reduced steps per rung for testing. Fix before doing actual runs 
!!!!!!!!!!!!!!!!!


rm: cannot remove ‘/home2/karwal/lkl_prof/lcdm_mp_mcmc/lkl_prof_-H0/20*’: No such file or directory
rm: cannot remove ‘/home2/karwal/lkl_prof/lcdm_mp_mcmc/lkl_prof_-H0/lkl_prof_-H0*’: No such file or directory


 /!\ Appending to an existing folder: using the log.param instead of
     /home2/karwal/lkl_prof/lcdm_mp_mcmc/lkl_prof_-H0/log.param
Running Monte Python v3.5.0

 /!\ Your code location in the log.param file is in contradiction with your
     .conf file. I will use the one from log.param.
with CLASS v2.9.4
 /!\ CLASS set to version 8b6aceabc2471195f295fd59ea53a9a82ae962ca, wrt. the one
     used in the log.param: 3b5dbac0808a259386eb9bab56d7c3523471519e.

Testing likelihoods for:
 ->Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing, bao_smallz_2014, bao_fs_boss_dr12, Pantheon

----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-

----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version plc_3.1
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp

1  1905.34	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.638769e+01	8.333935e-01	6.502123e+00	2.493720e+02	5.660142e+01	5.931897e+01	1.238495e+02	8.456548e-01	9.076860e+00	1.126223e+01	2.027565e+01	9.510054e+01	1.172101e-01	1.355537e-01	4.681149e-01	2.191781e-01	6.504650e-01	2.066385e+00	9.996523e+02	9.982747e+02	1.000715e+00	-1.942125e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
2  1905.27	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.520674e+01	8.777222e-01	6.697767e+00	2.533440e+02	5.697866e+01	6.088108e+01	1.255236e+02	7.468581e-01	8.774243e+00	1.114160e+01	2.041216e+01	9.582861e+01	1.157987e-01	1.350957e-01	4.710988e-01	2.270634e-01	6.645385e-01	2.108057e+00	9.997123e+02	9.981342e+02	1.000659e+00	-1.942101e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
1  1905.27	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.495379e+01	8.596125e-01	6.764163e+00	2

1  1905.48	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.661909e+01	7.999894e-01	6.398064e+00	2.568903e+02	5.661930e+01	5.804731e+01	1.236596e+02	7.065118e-01	9.004984e+00	1.115355e+01	2.025619e+01	9.516557e+01	1.242538e-01	1.399023e-01	4.539884e-01	2.345015e-01	6.428681e-01	1.996040e+00	9.995812e+02	9.983354e+02	1.000652e+00	-1.942118e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
1  1905.47	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.450131e+01	8.146604e-01	6.755133e+00	2.553753e+02	5.561494e+01	5.921832e+01	1.259021e+02	6.337316e-01	9.049766e+00	1.127181e+01	2.110359e+01	9.762504e+01	1.169906e-01	1.417740e-01	4.627816e-01	2.329338e-01	6.804621e-01	2.109433e+00	9.996398e+02	9.982491e+02	1.000631e+00	-1.942105e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
1  1905.48	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.421846e+01	8.186777e-01	6.705911e+00	2

1  1905.5	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.661991e+01	8.397739e-01	6.269080e+00	2.595533e+02	5.609226e+01	5.844437e+01	1.240397e+02	8.275427e-01	9.030443e+00	1.106826e+01	2.007236e+01	9.446016e+01	1.200338e-01	1.414648e-01	4.612924e-01	2.302987e-01	6.546773e-01	2.029177e+00	9.997063e+02	9.984152e+02	1.000644e+00	-1.942138e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
1  1905.68	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.360802e+01	8.394348e-01	6.562369e+00	2.582696e+02	5.578253e+01	5.887628e+01	1.256264e+02	1.107626e+00	9.017414e+00	1.126959e+01	2.128944e+01	9.904539e+01	1.167401e-01	1.422530e-01	4.496595e-01	2.375447e-01	6.804981e-01	2.059465e+00	9.996337e+02	9.982488e+02	1.000696e+00	-1.942097e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
1  1905.47	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.707136e+01	8.086767e-01	6.271233e+00	2.

1  1905.58	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.355185e+01	8.722743e-01	7.081451e+00	2.538828e+02	5.542392e+01	6.041483e+01	1.265850e+02	4.681953e-01	8.592371e+00	1.133264e+01	2.156862e+01	9.928343e+01	1.135162e-01	1.448183e-01	4.468491e-01	2.348315e-01	6.782700e-01	2.109607e+00	9.996452e+02	9.982192e+02	1.000667e+00	-1.942130e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
1  1905.59	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.349677e+01	8.815788e-01	7.255726e+00	2.516072e+02	5.539744e+01	6.123565e+01	1.270267e+02	3.491518e-01	8.720407e+00	1.137078e+01	2.168836e+01	9.938986e+01	1.178748e-01	1.448095e-01	4.543728e-01	2.316200e-01	6.801346e-01	2.115676e+00	9.996208e+02	9.982482e+02	1.000620e+00	-1.942123e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
2  1905.49	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.728625e+01	7.564573e-01	6.119376e+00	2

1  1905.73	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.717196e+01	6.826239e-01	5.972196e+00	2.597667e+02	5.456562e+01	5.433765e+01	1.225142e+02	9.063395e-01	8.743721e+00	1.109850e+01	1.929728e+01	9.374677e+01	1.163770e-01	1.315196e-01	4.242366e-01	2.101457e-01	6.624532e-01	1.983668e+00	9.994981e+02	9.983747e+02	1.000842e+00	-1.942166e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
2  1905.54	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.375122e+01	9.334412e-01	7.303455e+00	2.495263e+02	5.576901e+01	6.218194e+01	1.265802e+02	4.016530e-01	8.845812e+00	1.128459e+01	2.181399e+01	9.902269e+01	1.176402e-01	1.431283e-01	4.620288e-01	2.188587e-01	6.763482e-01	2.110191e+00	9.996824e+02	9.982112e+02	1.000632e+00	-1.942133e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
2  1905.7	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.716992e+01	6.942456e-01	6.098173e+00	2.

1  1905.5	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.716372e+01	7.195809e-01	6.101143e+00	2.586064e+02	5.481661e+01	5.556593e+01	1.230213e+02	5.905916e-01	8.738480e+00	1.114661e+01	1.951947e+01	9.389230e+01	1.159494e-01	1.280362e-01	4.477117e-01	2.103723e-01	6.549671e-01	2.070547e+00	9.995600e+02	9.983438e+02	1.000729e+00	-1.942167e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
1  1905.45	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.406965e+01	8.795734e-01	7.279381e+00	2.456974e+02	5.367221e+01	6.053977e+01	1.260147e+02	6.012418e-01	8.850533e+00	1.125170e+01	2.118819e+01	9.783871e+01	1.200962e-01	1.429239e-01	4.745045e-01	2.330420e-01	6.907326e-01	2.109868e+00	9.996558e+02	9.981910e+02	1.000725e+00	-1.942159e+01	1.379165e+01	1.446098e+02	1.041987e+00	8.129520e-01	3.130803e-01	6.868403e-01	
1  1905.54	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.700181e+01	7.147062e-01	6.052327e+00	2.

1  1905.63	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.580464e+01	6.752953e-01	6.058508e+00	2.553963e+02	5.329125e+01	5.432115e+01	1.240781e+02	1.019426e+00	9.095771e+00	1.131491e+01	1.972259e+01	9.530583e+01	1.219912e-01	1.358463e-01	4.441156e-01	2.117454e-01	6.496938e-01	2.063090e+00	9.995066e+02	9.983914e+02	1.000782e+00	-1.942133e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
1  1905.63	2.235342e+00	1.197080e-01	9.667632e-01	2.097660e+00	5.348980e-02	4.580464e+01	6.752953e-01	6.058508e+00	2.553963e+02	5.329125e+01	5.432115e+01	1.240781e+02	1.019426e+00	9.095771e+00	1.131491e+01	1.972259e+01	9.530583e+01	1.219912e-01	1.358463e-01	4.441156e-01	2.117454e-01	6.496938e-01	2.063090e+00	9.995066e+02	9.983914e+02	1.000782e+00	-1.942131e+01	1.379173e+01	1.446102e+02	1.041982e+00	8.096852e-01	3.130737e-01	6.868468e-01	
3  1905.66	2.235286e+00	1.197116e-01	9.675308e-01	2.113313e+00	5.731206e-02	4.364570e+01	8.875535e-01	7.427305e+00	2

 -> Computing histograms for  tau_reio
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_cib_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  xi_sz_cib
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_sz
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  ps_A_100_100
 /!\ could not derive minimum credible intervals for this multimoda

Creating /home2/karwal/lkl_prof/lcdm_mp_mcmc/lkl_prof_-H0/2022-08-23_100__3.txt


Input covariance matrix:
['omega_b', 'omega_cdm', 'H0', 'n_s', 'A_s', 'tau_reio', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'calib_100T', 'calib_217T', 'A_planck', 'M', 'age', 'rs_rec', '100*theta_s', 'sigma8', 'Omega_m', 'Omega_Lambda']
[[ 1.75e-08 -4.88e-08  3.51e-05 ... -4.02e-08 -3.91e-07  3.91e-07]
 [-4.88e-08  8.24e-07 -3.45e-04 ...  1.22e-06  4.86e-06 -4.87e-06]
 [ 3.51e-05 -3.45e-04  1.68e-01 ... -4.25e-04 -2.22e-03  2.22e-03]
 ...
 [-4.02e-08  1.22e-06 -4.25e-04 ...  3.48e-05  6.49e-06 -6.49e-06]
 [-3.91e-07  4.86e-06 -2.22e-03 ...  6.49e-06  3.02e-05 -3.02e-05]
 [ 3.91e-07 -4.87e-06  2.22e-03 ... -6.49e-06 -3.02e-05  3.02e-05]]

First treatment (scal

----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version plc_3.1
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp

2  1905.11	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.579032e+01	8.719497e-01	6.448871e+00	2.512714e+02	5.619844e+01	5.885372e+01	1.233099e+02	1.127952e+00	8.774986e+00	1.094387e+01	2.014241e+01	9.550021e+01	1.155344e-01	1.363805e-01	4.750262e-01	2.274630e-01	6.565861e-01	2.082346e+00	9.997041e+02	9.982448e+02	1.000830e+00	-1.942074e+01	1.379078e+01	1.445906e+02	1.041943e+00	8.127217e-01	3.131505e-01	6.867700e-01	
1  1905.11	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.567282e+01	8.754648e-01	6.443031e+00	2.511446e+02	5.628747e+01	5.915790e+01	1.237127e+02	1.087549e+00	8.795960e+00	1.093366e+01	2.001926e+01	9.528616e+01	1.146841e-01	1.356273e-01	4.764704e-01	2.264656e-01	6.578368e-01	2.090169e+00	9.997063e+02	9.982376e+02	1.000815e+00	-1.942076e+01	1.379078e+01	1.445906e+02	1.041943e+00	8.127217e-01	3.131505e-01	6.867700e-01	
1  1905.09	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.559314e+01	8.609039e-01	6.551798e+00	2

2  1905.06	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.589232e+01	8.301733e-01	6.784826e+00	2.487031e+02	5.485144e+01	5.828608e+01	1.234230e+02	7.979457e-01	8.804147e+00	1.095313e+01	2.028976e+01	9.539466e+01	1.124790e-01	1.340031e-01	4.858590e-01	2.231592e-01	6.601941e-01	2.086120e+00	9.997233e+02	9.981432e+02	1.000836e+00	-1.942097e+01	1.379078e+01	1.445906e+02	1.041943e+00	8.127217e-01	3.131505e-01	6.867700e-01	
1  1905.06	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.580238e+01	8.276994e-01	6.821762e+00	2.487958e+02	5.477010e+01	5.842393e+01	1.236745e+02	7.420511e-01	8.821570e+00	1.103307e+01	2.037382e+01	9.558035e+01	1.125499e-01	1.336052e-01	4.850236e-01	2.231576e-01	6.604821e-01	2.088512e+00	9.997105e+02	9.981204e+02	1.000849e+00	-1.942097e+01	1.379078e+01	1.445906e+02	1.041943e+00	8.127217e-01	3.131505e-01	6.867700e-01	
3  1905.06	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.584922e+01	8.281330e-01	6.841186e+00	2

2  1905.07	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.538307e+01	8.191886e-01	6.643182e+00	2.501401e+02	5.467312e+01	5.731658e+01	1.235796e+02	9.726250e-01	8.863939e+00	1.103458e+01	2.045958e+01	9.597617e+01	1.091663e-01	1.311869e-01	4.667738e-01	2.219684e-01	6.613792e-01	2.056468e+00	9.996669e+02	9.981336e+02	1.000900e+00	-1.942102e+01	1.379078e+01	1.445906e+02	1.041943e+00	8.127217e-01	3.131505e-01	6.867700e-01	
1  1905.21	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.572650e+01	8.322260e-01	6.557785e+00	2.542136e+02	5.597416e+01	5.867186e+01	1.242995e+02	9.540106e-01	8.883675e+00	1.103306e+01	2.010511e+01	9.523842e+01	1.175562e-01	1.358581e-01	4.756733e-01	2.212946e-01	6.686147e-01	2.110725e+00	9.996738e+02	9.981833e+02	1.000588e+00	-1.942169e+01	1.379043e+01	1.445987e+02	1.042037e+00	8.127921e-01	3.131784e-01	6.867422e-01	
1  1905.07	2.237360e+00	1.197229e-01	9.671046e-01	2.113242e+00	5.701986e-02	4.543279e+01	8.238266e-01	6.691607e+00	2

4  1905.18	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.618125e+01	7.959008e-01	6.385062e+00	2.560234e+02	5.530678e+01	5.693072e+01	1.229138e+02	1.109663e+00	8.976568e+00	1.104692e+01	2.002623e+01	9.508092e+01	1.164175e-01	1.353391e-01	4.860866e-01	2.222604e-01	6.689141e-01	2.088466e+00	9.996872e+02	9.981900e+02	1.000597e+00	-1.942171e+01	1.379043e+01	1.445987e+02	1.042037e+00	8.127921e-01	3.131784e-01	6.867422e-01	
1  1905.19	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.618835e+01	7.995844e-01	6.341779e+00	2.567947e+02	5.533506e+01	5.688992e+01	1.228258e+02	1.200076e+00	8.978841e+00	1.104944e+01	1.997333e+01	9.501191e+01	1.162203e-01	1.365057e-01	4.871546e-01	2.238957e-01	6.707857e-01	2.079246e+00	9.996704e+02	9.981879e+02	1.000623e+00	-1.942170e+01	1.379043e+01	1.445987e+02	1.042037e+00	8.127921e-01	3.131784e-01	6.867422e-01	
2  1905.19	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.625098e+01	7.973815e-01	6.295139e+00	2

1  1905.2	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.593093e+01	8.081893e-01	6.485037e+00	2.564704e+02	5.595843e+01	5.756821e+01	1.232552e+02	9.744907e-01	8.726941e+00	1.120019e+01	2.043440e+01	9.568078e+01	1.183792e-01	1.381481e-01	4.756682e-01	2.270203e-01	6.616096e-01	2.055572e+00	9.996957e+02	9.981794e+02	1.000578e+00	-1.942165e+01	1.379043e+01	1.445987e+02	1.042037e+00	8.127921e-01	3.131784e-01	6.867422e-01	
2  1905.2	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.600645e+01	8.100069e-01	6.448497e+00	2.559192e+02	5.592717e+01	5.735059e+01	1.229502e+02	1.017490e+00	8.718598e+00	1.117195e+01	2.041214e+01	9.558893e+01	1.189918e-01	1.379246e-01	4.743397e-01	2.273647e-01	6.629082e-01	2.055074e+00	9.996960e+02	9.981604e+02	1.000576e+00	-1.942167e+01	1.379043e+01	1.445987e+02	1.042037e+00	8.127921e-01	3.131784e-01	6.867422e-01	
1  1905.2	2.235203e+00	1.197571e-01	9.670851e-01	2.112137e+00	5.707184e-02	4.603096e+01	7.986596e-01	6.457160e+00	2.56

 -> Computing histograms for  tau_reio
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_cib_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  xi_sz_cib
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_sz
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  ps_A_100_100
 /!\ could not derive minimum credible intervals for this multimoda

Creating /home2/karwal/lkl_prof/lcdm_mp_mcmc/lkl_prof_-H0/2022-08-23_100__5.txt


Input covariance matrix:
['omega_b', 'omega_cdm', 'H0', 'n_s', 'A_s', 'tau_reio', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'calib_100T', 'calib_217T', 'A_planck', 'M', 'age', 'rs_rec', '100*theta_s', 'sigma8', 'Omega_m', 'Omega_Lambda']
[[ 1.75e-08 -4.88e-08  3.51e-05 ... -4.02e-08 -3.91e-07  3.91e-07]
 [-4.88e-08  8.24e-07 -3.45e-04 ...  1.22e-06  4.86e-06 -4.87e-06]
 [ 3.51e-05 -3.45e-04  1.68e-01 ... -4.25e-04 -2.22e-03  2.22e-03]
 ...
 [-4.02e-08  1.22e-06 -4.25e-04 ...  3.48e-05  6.49e-06 -6.49e-06]
 [-3.91e-07  4.86e-06 -2.22e-03 ...  6.49e-06  3.02e-05 -3.02e-05]
 [ 3.91e-07 -4.87e-06  2.22e-03 ... -6.49e-06 -3.02e-05  3.02e-05]]

First treatment (scal

----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version plc_3.1
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp

2  1904.99	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.513709e+01	8.452986e-01	6.664413e+00	2.519861e+02	5.507482e+01	5.796785e+01	1.238575e+02	1.026633e+00	8.740349e+00	1.093466e+01	2.040997e+01	9.598300e+01	1.100913e-01	1.318815e-01	4.714306e-01	2.233965e-01	6.608616e-01	2.070061e+00	9.997413e+02	9.981938e+02	1.000882e+00	-1.942170e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
1  1904.99	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.508560e+01	8.502747e-01	6.644395e+00	2.516436e+02	5.510321e+01	5.801917e+01	1.239509e+02	1.021914e+00	8.761661e+00	1.091843e+01	2.040167e+01	9.597543e+01	1.098276e-01	1.320554e-01	4.723639e-01	2.230872e-01	6.599158e-01	2.069213e+00	9.997436e+02	9.981976e+02	1.000876e+00	-1.942173e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
9  1904.97	2.238831e+00	1.197064e-01	9.671551e-01	2.110250e+00	5.643141e-02	4.518769e+01	8.661973e-01	6.574346e+00	2

1  1904.98	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.511682e+01	8.447337e-01	6.630087e+00	2.517319e+02	5.493244e+01	5.787478e+01	1.240771e+02	1.060152e+00	8.838137e+00	1.097893e+01	2.038047e+01	9.603745e+01	1.125600e-01	1.329552e-01	4.751225e-01	2.223175e-01	6.608984e-01	2.078016e+00	9.997532e+02	9.982117e+02	1.000911e+00	-1.942170e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
1  1904.97	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.513134e+01	8.409407e-01	6.618920e+00	2.518029e+02	5.487580e+01	5.780214e+01	1.240407e+02	1.056392e+00	8.856914e+00	1.098624e+01	2.035873e+01	9.602297e+01	1.116546e-01	1.325168e-01	4.749480e-01	2.225295e-01	6.615962e-01	2.080922e+00	9.997608e+02	9.982118e+02	1.000921e+00	-1.942172e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
4  1904.95	2.238831e+00	1.197064e-01	9.671551e-01	2.110250e+00	5.643141e-02	4.509649e+01	8.495635e-01	6.528343e+00	2

1  1904.95	2.238831e+00	1.197064e-01	9.671551e-01	2.110250e+00	5.643141e-02	4.524937e+01	8.488000e-01	6.543893e+00	2.516623e+02	5.495420e+01	5.771071e+01	1.236522e+02	1.095749e+00	8.811901e+00	1.110801e+01	2.040300e+01	9.594532e+01	1.129481e-01	1.355952e-01	4.813677e-01	2.258437e-01	6.641971e-01	2.063192e+00	9.997147e+02	9.982051e+02	1.000827e+00	-1.942183e+01	1.379083e+01	1.445833e+02	1.041885e+00	8.119950e-01	3.131466e-01	6.867739e-01	
3  1904.96	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.550516e+01	8.050980e-01	6.539294e+00	2.522556e+02	5.437048e+01	5.675009e+01	1.234253e+02	1.060484e+00	8.915069e+00	1.097192e+01	2.007031e+01	9.537825e+01	1.118443e-01	1.338734e-01	4.769032e-01	2.251188e-01	6.604499e-01	2.084457e+00	9.997580e+02	9.981866e+02	1.000914e+00	-1.942177e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
2  1904.96	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.554946e+01	8.018584e-01	6.532553e+00	2

2  1904.96	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.557700e+01	7.923926e-01	6.447316e+00	2.535501e+02	5.431439e+01	5.608554e+01	1.230722e+02	1.106200e+00	8.838821e+00	1.102800e+01	2.009204e+01	9.542166e+01	1.133837e-01	1.333471e-01	4.798362e-01	2.223332e-01	6.641007e-01	2.090911e+00	9.997443e+02	9.981848e+02	1.000932e+00	-1.942179e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
2  1904.95	2.239228e+00	1.197075e-01	9.671807e-01	2.114422e+00	5.734092e-02	4.557700e+01	7.923926e-01	6.447316e+00	2.535501e+02	5.431439e+01	5.608554e+01	1.230722e+02	1.106200e+00	8.838821e+00	1.102800e+01	2.009204e+01	9.542166e+01	1.133837e-01	1.333471e-01	4.798362e-01	2.223332e-01	6.641007e-01	2.090911e+00	9.997443e+02	9.981848e+02	1.000932e+00	-1.942222e+01	1.379069e+01	1.445800e+02	1.041876e+00	8.127832e-01	3.131577e-01	6.867629e-01	
7  1904.94	2.238831e+00	1.197064e-01	9.671551e-01	2.110250e+00	5.643141e-02	4.520789e+01	8.139442e-01	6.565463e+00	2

 -> Computing histograms for  gal545_A_143_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  gal545_A_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  galf_TE_A_100
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  galf_TE_A_100_143
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  galf_TE_A_100_217
 /!\ could not derive minimum cred

----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version plc_3.1
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp

1  1905.19	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.450129e+01	8.992006e-01	6.596384e+00	2.521446e+02	5.624268e+01	5.944265e+01	1.256984e+02	6.178361e-01	8.532109e+00	1.106935e+01	2.075597e+01	9.663001e+01	1.180159e-01	1.372205e-01	4.959838e-01	2.264412e-01	6.693422e-01	2.101447e+00	9.997869e+02	9.982055e+02	1.000977e+00	-1.942443e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
3  1905.22	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.470562e+01	8.236332e-01	6.567562e+00	2.505109e+02	5.465749e+01	5.741688e+01	1.243352e+02	7.360721e-01	8.855048e+00	1.127790e+01	2.054578e+01	9.657019e+01	1.143791e-01	1.360107e-01	4.805150e-01	2.214791e-01	6.645646e-01	2.062577e+00	9.996661e+02	9.982168e+02	1.000440e+00	-1.942356e+01	1.379389e+01	1.445243e+02	1.041789e+00	8.126583e-01	3.145521e-01	6.853682e-01	
1  1905.2	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.471582e+01	8.280109e-01	6.669433e+00	2.

1  1905.25	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.450822e+01	9.338778e-01	6.145428e+00	2.503369e+02	5.533389e+01	5.816930e+01	1.247283e+02	1.204079e+00	8.743732e+00	1.127744e+01	2.034573e+01	9.587781e+01	1.213745e-01	1.370428e-01	4.832424e-01	2.240352e-01	6.836898e-01	2.119385e+00	9.997077e+02	9.981949e+02	1.001062e+00	-1.942461e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
1  1905.38	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.362775e+01	8.863044e-01	6.862191e+00	2.497218e+02	5.557087e+01	5.940765e+01	1.266677e+02	1.411679e-01	9.078171e+00	1.150795e+01	2.120330e+01	9.762258e+01	1.125060e-01	1.361334e-01	4.914030e-01	2.239549e-01	6.450928e-01	2.034916e+00	9.997887e+02	9.981443e+02	1.000330e+00	-1.942371e+01	1.379389e+01	1.445243e+02	1.041789e+00	8.126583e-01	3.145521e-01	6.853682e-01	
1  1905.31	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.442241e+01	9.267786e-01	6.194915e+00	2

1  1905.39	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.460432e+01	9.120449e-01	6.139720e+00	2.520369e+02	5.682706e+01	5.902560e+01	1.257143e+02	9.378354e-01	8.694621e+00	1.143869e+01	2.066283e+01	9.618086e+01	1.157468e-01	1.346370e-01	4.777179e-01	2.201683e-01	6.914468e-01	2.119436e+00	9.997961e+02	9.982123e+02	1.000967e+00	-1.942420e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
1  1905.44	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.320718e+01	8.944491e-01	6.665306e+00	2.527034e+02	5.711771e+01	5.911136e+01	1.265213e+02	1.567581e-01	8.850268e+00	1.141886e+01	2.176448e+01	9.886939e+01	1.122758e-01	1.399407e-01	4.838282e-01	2.306496e-01	6.474454e-01	2.047070e+00	9.998087e+02	9.982261e+02	1.000326e+00	-1.942365e+01	1.379389e+01	1.445243e+02	1.041789e+00	8.126583e-01	3.145521e-01	6.853682e-01	
1  1905.41	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.544138e+01	9.082865e-01	6.126797e+00	2

1  1905.39	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.531229e+01	8.914305e-01	6.506044e+00	2.531700e+02	5.700332e+01	5.963885e+01	1.253937e+02	8.496997e-01	8.597390e+00	1.127090e+01	2.052366e+01	9.555454e+01	1.115677e-01	1.350085e-01	4.689894e-01	2.177990e-01	6.800750e-01	2.092690e+00	9.999297e+02	9.982227e+02	1.001106e+00	-1.942419e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
2  1905.48	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.364781e+01	8.375756e-01	6.181562e+00	2.554713e+02	5.644854e+01	5.679578e+01	1.255508e+02	4.549186e-01	8.873550e+00	1.136169e+01	2.134652e+01	9.841727e+01	1.117260e-01	1.425704e-01	4.784523e-01	2.405523e-01	6.604662e-01	2.114013e+00	9.997965e+02	9.982603e+02	1.000360e+00	-1.942361e+01	1.379389e+01	1.445243e+02	1.041789e+00	8.126583e-01	3.145521e-01	6.853682e-01	
2  1905.39	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.602709e+01	8.801882e-01	6.504209e+00	2

2  1905.55	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.476022e+01	8.807148e-01	6.448530e+00	2.544690e+02	5.736052e+01	6.007109e+01	1.276039e+02	8.438385e-01	8.814163e+00	1.121704e+01	2.019580e+01	9.516428e+01	1.149988e-01	1.356406e-01	4.714850e-01	2.203556e-01	6.693182e-01	2.035869e+00	9.999789e+02	9.981588e+02	1.001257e+00	-1.942425e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
1  1905.59	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.495022e+01	8.640783e-01	6.300151e+00	2.557228e+02	5.749218e+01	5.944928e+01	1.269698e+02	9.473937e-01	8.898418e+00	1.123107e+01	2.006924e+01	9.488931e+01	1.149747e-01	1.363167e-01	4.695590e-01	2.186916e-01	6.673707e-01	2.027520e+00	9.999813e+02	9.981566e+02	1.001202e+00	-1.942413e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
3  1905.51	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.443091e+01	8.826712e-01	6.332210e+00	2

2  1905.64	2.239512e+00	1.199158e-01	9.673632e-01	2.110329e+00	5.660192e-02	4.271954e+01	8.521385e-01	5.937695e+00	2.574455e+02	5.726171e+01	5.683066e+01	1.268447e+02	3.725219e-01	9.086807e+00	1.094137e+01	2.115244e+01	9.875861e+01	1.103163e-01	1.394175e-01	4.576659e-01	2.411253e-01	6.679312e-01	2.116666e+00	9.997395e+02	9.981269e+02	1.000424e+00	-1.942391e+01	1.379389e+01	1.445243e+02	1.041789e+00	8.126583e-01	3.145521e-01	6.853682e-01	
1  1905.53	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.543796e+01	8.566985e-01	5.994518e+00	2.607837e+02	5.771184e+01	5.852645e+01	1.252998e+02	1.139925e+00	8.830080e+00	1.109029e+01	1.944451e+01	9.431319e+01	1.153797e-01	1.313285e-01	4.574945e-01	2.135940e-01	6.662933e-01	2.021514e+00	9.999460e+02	9.982120e+02	1.001252e+00	-1.942428e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
1  1905.55	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.564896e+01	8.626604e-01	5.915582e+00	2

2  1905.47	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.680747e+01	8.267579e-01	6.125574e+00	2.576757e+02	5.760102e+01	5.834140e+01	1.233795e+02	7.402544e-01	8.949659e+00	1.072996e+01	1.895771e+01	9.318175e+01	1.188065e-01	1.374040e-01	4.668560e-01	2.169348e-01	6.555355e-01	1.999749e+00	9.999194e+02	9.982716e+02	1.001104e+00	-1.942436e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
2  1905.47	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.680747e+01	8.267579e-01	6.125574e+00	2.576757e+02	5.760102e+01	5.834140e+01	1.233795e+02	7.402544e-01	8.949659e+00	1.072996e+01	1.895771e+01	9.318175e+01	1.188065e-01	1.374040e-01	4.668560e-01	2.169348e-01	6.555355e-01	1.999749e+00	9.999194e+02	9.982716e+02	1.001104e+00	-1.942443e+01	1.379495e+01	1.445515e+02	1.041872e+00	8.130105e-01	3.144661e-01	6.854542e-01	
1  1905.51	2.236232e+00	1.199095e-01	9.669082e-01	2.111911e+00	5.622381e-02	4.680747e+01	8.267579e-01	6.125574e+00	2

 -> Computing histograms for  A_cib_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  xi_sz_cib
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_sz
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  ps_A_100_100
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  ps_A_143_143
 /!\ could not derive minimum credible intervals for this multi

Creating /home2/karwal/lkl_prof/lcdm_mp_mcmc/lkl_prof_-H0/2022-08-23_100__3.txt


Input covariance matrix:
['omega_b', 'omega_cdm', 'H0', 'n_s', 'A_s', 'tau_reio', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'calib_100T', 'calib_217T', 'A_planck', 'M', 'age', 'rs_rec', '100*theta_s', 'sigma8', 'Omega_m', 'Omega_Lambda']
[[ 1.75e-08 -4.88e-08  3.51e-05 ... -4.02e-08 -3.91e-07  3.91e-07]
 [-4.88e-08  8.24e-07 -3.45e-04 ...  1.22e-06  4.86e-06 -4.87e-06]
 [ 3.51e-05 -3.45e-04  1.68e-01 ... -4.25e-04 -2.22e-03  2.22e-03]
 ...
 [-4.02e-08  1.22e-06 -4.25e-04 ...  3.48e-05  6.49e-06 -6.49e-06]
 [-3.91e-07  4.86e-06 -2.22e-03 ...  6.49e-06  3.02e-05 -3.02e-05]
 [ 3.91e-07 -4.87e-06  2.22e-03 ... -6.49e-06 -3.02e-05  3.02e-05]]

First treatment (scal

----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version plc_3.1
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp

2  1905.09	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.511602e+01	7.967991e-01	6.556082e+00	2.521030e+02	5.442485e+01	5.678999e+01	1.240149e+02	8.679287e-01	8.809601e+00	1.114209e+01	2.030954e+01	9.594069e+01	1.139988e-01	1.347088e-01	4.845652e-01	2.228287e-01	6.701589e-01	2.103653e+00	9.996948e+02	9.981700e+02	1.001164e+00	-1.942426e+01	1.379435e+01	1.445375e+02	1.041834e+00	8.124765e-01	3.145142e-01	6.854061e-01	
2  1905.08	2.236391e+00	1.199263e-01	9.669489e-01	2.111090e+00	5.603622e-02	4.552863e+01	7.988158e-01	6.655254e+00	2.510082e+02	5.483081e+01	5.740545e+01	1.241922e+02	7.212445e-01	8.881659e+00	1.117746e+01	2.048693e+01	9.606856e+01	1.167574e-01	1.356640e-01	4.827259e-01	2.243854e-01	6.641043e-01	2.069077e+00	9.996924e+02	9.982322e+02	1.001196e+00	-1.942460e+01	1.379445e+01	1.445460e+02	1.041885e+00	8.129270e-01	3.145066e-01	6.854137e-01	
1  1905.09	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.507169e+01	7.935193e-01	6.606674e+00	2

7  1905.09	2.236391e+00	1.199263e-01	9.669489e-01	2.111090e+00	5.603622e-02	4.494278e+01	8.053455e-01	6.571359e+00	2.533469e+02	5.504364e+01	5.765491e+01	1.249436e+02	8.290120e-01	8.887444e+00	1.108525e+01	2.040645e+01	9.641444e+01	1.150848e-01	1.361703e-01	4.786402e-01	2.272567e-01	6.668241e-01	2.066891e+00	9.997035e+02	9.982166e+02	1.001211e+00	-1.942458e+01	1.379445e+01	1.445460e+02	1.041885e+00	8.129270e-01	3.145066e-01	6.854137e-01	
2  1905.1	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.555936e+01	7.929638e-01	6.809465e+00	2.494935e+02	5.433763e+01	5.722432e+01	1.239683e+02	6.951315e-01	8.991715e+00	1.111970e+01	2.036988e+01	9.576714e+01	1.173107e-01	1.358022e-01	4.859014e-01	2.240076e-01	6.691190e-01	2.084470e+00	9.996845e+02	9.981861e+02	1.001209e+00	-1.942427e+01	1.379435e+01	1.445375e+02	1.041834e+00	8.124765e-01	3.145142e-01	6.854061e-01	
1  1905.08	2.236391e+00	1.199263e-01	9.669489e-01	2.111090e+00	5.603622e-02	4.514382e+01	8.112546e-01	6.647294e+00	2.

1  1905.09	2.236391e+00	1.199263e-01	9.669489e-01	2.111090e+00	5.603622e-02	4.557108e+01	7.998966e-01	6.869664e+00	2.488193e+02	5.434192e+01	5.790929e+01	1.244818e+02	6.651521e-01	8.928870e+00	1.109533e+01	2.038484e+01	9.572715e+01	1.128855e-01	1.348163e-01	4.736134e-01	2.282305e-01	6.669165e-01	2.062186e+00	9.997424e+02	9.981818e+02	1.001184e+00	-1.942461e+01	1.379445e+01	1.445460e+02	1.041885e+00	8.129270e-01	3.145066e-01	6.854137e-01	
5  1905.1	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.503145e+01	7.721543e-01	6.536226e+00	2.516270e+02	5.395435e+01	5.607941e+01	1.242142e+02	1.023555e+00	8.991898e+00	1.111508e+01	2.017544e+01	9.583397e+01	1.178676e-01	1.360321e-01	4.802450e-01	2.228204e-01	6.629086e-01	2.055185e+00	9.997059e+02	9.981411e+02	1.001207e+00	-1.942419e+01	1.379435e+01	1.445375e+02	1.041834e+00	8.124765e-01	3.145142e-01	6.854061e-01	
1  1905.1	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.488957e+01	7.668481e-01	6.549897e+00	2.5

1  1905.09	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.623462e+01	7.419600e-01	6.608608e+00	2.521496e+02	5.345580e+01	5.541895e+01	1.227068e+02	9.321810e-01	8.948326e+00	1.108915e+01	2.007225e+01	9.514204e+01	1.166199e-01	1.370945e-01	4.843538e-01	2.271651e-01	6.689629e-01	2.074871e+00	9.997197e+02	9.982631e+02	1.001212e+00	-1.942419e+01	1.379435e+01	1.445375e+02	1.041834e+00	8.124765e-01	3.145142e-01	6.854061e-01	
1  1905.12	2.236391e+00	1.199263e-01	9.669489e-01	2.111090e+00	5.603622e-02	4.570515e+01	7.842152e-01	6.967028e+00	2.478967e+02	5.403221e+01	5.742206e+01	1.241605e+02	6.799259e-01	9.001895e+00	1.114095e+01	2.049985e+01	9.572480e+01	1.146102e-01	1.357145e-01	4.655004e-01	2.284941e-01	6.667080e-01	2.068141e+00	9.997098e+02	9.981821e+02	1.001248e+00	-1.942466e+01	1.379445e+01	1.445460e+02	1.041885e+00	8.129270e-01	3.145066e-01	6.854137e-01	
2  1905.09	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.623865e+01	7.474289e-01	6.618063e+00	2

2  1905.09	2.237836e+00	1.199153e-01	9.667859e-01	2.109743e+00	5.571334e-02	4.603222e+01	7.484719e-01	6.659351e+00	2.507906e+02	5.315470e+01	5.583781e+01	1.231285e+02	9.234513e-01	9.057968e+00	1.108304e+01	2.007957e+01	9.527258e+01	1.100901e-01	1.338402e-01	4.828683e-01	2.278620e-01	6.674723e-01	2.070101e+00	9.997590e+02	9.982521e+02	1.001151e+00	-1.942432e+01	1.379435e+01	1.445375e+02	1.041834e+00	8.124765e-01	3.145142e-01	6.854061e-01	
6  1905.08	2.238114e+00	1.199357e-01	9.667281e-01	2.110535e+00	5.596877e-02	4.603077e+01	7.480898e-01	6.662193e+00	2.507324e+02	5.311557e+01	5.580170e+01	1.230747e+02	9.277776e-01	9.058506e+00	1.108442e+01	2.008057e+01	9.525813e+01	1.100901e-01	1.338175e-01	4.828860e-01	2.278483e-01	6.674371e-01	2.069637e+00	9.997590e+02	9.982522e+02	1.001057e+00	-1.942443e+01	1.379373e+01	1.445301e+02	1.041848e+00	8.126810e-01	3.145651e-01	6.853552e-01	

#  100 steps done, acceptance rate: 0.54
7  1905.11	2.236391e+00	1.199263e-01	9.669489e-01	2.111090e+00	5.603622e-0

 -> Computing histograms for  galf_TE_A_100_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  galf_TE_A_143
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  galf_TE_A_143_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  galf_TE_A_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  calib_100T
 /!\ Polyfit may be poorly conditioned


----
clik version plc_3.1
  smica
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version plc_3.1
  simall simall_EE_BB_TE
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version plc_3.1
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home2/karwal/likelihoods/code/planck/code/plc_3.0/plc-3.1/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp

2  1905.08	2.237926e+00	1.199199e-01	9.666893e-01	2.110746e+00	5.599647e-02	4.578187e+01	7.884552e-01	6.700983e+00	2.531677e+02	5.480629e+01	5.750385e+01	1.238489e+02	6.893411e-01	8.935021e+00	1.107197e+01	2.017849e+01	9.546983e+01	1.122163e-01	1.342989e-01	4.798846e-01	2.244607e-01	6.624277e-01	2.086536e+00	9.997279e+02	9.981914e+02	1.001169e+00	-1.942428e+01	1.379421e+01	1.445356e+02	1.041837e+00	8.126537e-01	3.145262e-01	6.853942e-01	
1  1905.08	2.237926e+00	1.199199e-01	9.666893e-01	2.110746e+00	5.599647e-02	4.574830e+01	7.925409e-01	6.700284e+00	2.531796e+02	5.480507e+01	5.766461e+01	1.240374e+02	6.810144e-01	8.944845e+00	1.107513e+01	2.014092e+01	9.537037e+01	1.126240e-01	1.343151e-01	4.786208e-01	2.245732e-01	6.625984e-01	2.087100e+00	9.997427e+02	9.981804e+02	1.001160e+00	-1.942428e+01	1.379421e+01	1.445356e+02	1.041837e+00	8.126537e-01	3.145262e-01	6.853942e-01	
1  1905.08	2.237926e+00	1.199199e-01	9.666893e-01	2.110746e+00	5.599647e-02	4.579751e+01	7.932452e-01	6.727675e+00	2

2  1905.07	2.237668e+00	1.199279e-01	9.667576e-01	2.109891e+00	5.568960e-02	4.546087e+01	8.039583e-01	6.698266e+00	2.517340e+02	5.498018e+01	5.779440e+01	1.242217e+02	7.062045e-01	8.805810e+00	1.109654e+01	2.026076e+01	9.567353e+01	1.142313e-01	1.352782e-01	4.826502e-01	2.250570e-01	6.645257e-01	2.093427e+00	9.997034e+02	9.981680e+02	1.001243e+00	-1.942439e+01	1.379406e+01	1.445356e+02	1.041852e+00	8.125615e-01	3.145381e-01	6.853822e-01	
2  1905.07	2.237926e+00	1.199199e-01	9.666893e-01	2.110746e+00	5.599647e-02	4.601347e+01	7.895336e-01	6.699348e+00	2.518756e+02	5.466543e+01	5.749732e+01	1.236364e+02	6.577150e-01	9.015329e+00	1.110931e+01	2.016330e+01	9.526881e+01	1.137869e-01	1.342479e-01	4.834528e-01	2.245404e-01	6.651553e-01	2.090421e+00	9.997247e+02	9.981973e+02	1.001130e+00	-1.942425e+01	1.379421e+01	1.445356e+02	1.041837e+00	8.126537e-01	3.145262e-01	6.853942e-01	
1  1905.07	2.237926e+00	1.199199e-01	9.666893e-01	2.110746e+00	5.599647e-02	4.611172e+01	7.913076e-01	6.707211e+00	2

1  1905.07	2.237668e+00	1.199279e-01	9.667576e-01	2.109891e+00	5.568960e-02	4.546178e+01	7.870722e-01	6.704093e+00	2.522744e+02	5.482826e+01	5.746431e+01	1.243722e+02	6.820729e-01	8.775917e+00	1.108578e+01	2.022474e+01	9.562596e+01	1.135200e-01	1.339197e-01	4.802834e-01	2.255359e-01	6.644236e-01	2.091161e+00	9.997182e+02	9.981642e+02	1.001239e+00	-1.942437e+01	1.379406e+01	1.445356e+02	1.041852e+00	8.125615e-01	3.145381e-01	6.853822e-01	
4  1905.07	2.237926e+00	1.199199e-01	9.666893e-01	2.110746e+00	5.599647e-02	4.588891e+01	7.769899e-01	6.863885e+00	2.502885e+02	5.441117e+01	5.760888e+01	1.240092e+02	5.143830e-01	8.919686e+00	1.112815e+01	2.033815e+01	9.562923e+01	1.143586e-01	1.348048e-01	4.854187e-01	2.250244e-01	6.710838e-01	2.100273e+00	9.997127e+02	9.982241e+02	1.001117e+00	-1.942425e+01	1.379421e+01	1.445356e+02	1.041837e+00	8.126537e-01	3.145262e-01	6.853942e-01	
2  1905.06	2.237668e+00	1.199279e-01	9.667576e-01	2.109891e+00	5.568960e-02	4.548953e+01	7.847858e-01	6.716715e+00	2

3  1905.06	2.237668e+00	1.199279e-01	9.667576e-01	2.109891e+00	5.568960e-02	4.603989e+01	7.509706e-01	6.727716e+00	2.530443e+02	5.449096e+01	5.689863e+01	1.239191e+02	5.730383e-01	8.778834e+00	1.110765e+01	2.016603e+01	9.528473e+01	1.152958e-01	1.350891e-01	4.793071e-01	2.248265e-01	6.632946e-01	2.079968e+00	9.997282e+02	9.981897e+02	1.001234e+00	-1.942432e+01	1.379406e+01	1.445356e+02	1.041852e+00	8.125615e-01	3.145381e-01	6.853822e-01	
1  1905.06	2.237668e+00	1.199279e-01	9.667576e-01	2.109891e+00	5.568960e-02	4.610114e+01	7.535248e-01	6.722417e+00	2.535905e+02	5.465495e+01	5.710776e+01	1.239959e+02	5.335734e-01	8.796918e+00	1.109660e+01	2.013308e+01	9.521008e+01	1.152000e-01	1.348844e-01	4.794323e-01	2.242469e-01	6.626804e-01	2.078244e+00	9.997350e+02	9.981912e+02	1.001236e+00	-1.942432e+01	1.379406e+01	1.445356e+02	1.041852e+00	8.125615e-01	3.145381e-01	6.853822e-01	
5  1905.05	2.237668e+00	1.199279e-01	9.667576e-01	2.109891e+00	5.568960e-02	4.612022e+01	7.480071e-01	6.747779e+00	2

 -> Computing histograms for  tau_reio
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_cib_217
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  xi_sz_cib
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  A_sz
 /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)
 -> Computing histograms for  ps_A_100_100
 /!\ could not derive minimum credible intervals for this multimoda

AttributeError: 'numpy.ndarray' object has no attribute 'index'

### Check output

In [ ]:
lkl_prof_output = test.full_lkl_prof_dict()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(lkl_prof_output['H0'], lkl_prof_output['-logLike'])